// Code generated by gobind. DO NOT EDIT.

// Java class go.kipfs.core.ByteReader is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=go.kipfs kipfs/core
//go:build  linux || windows 
//+build linux, windows 
package go.kipfs.core;

import go.Seq;

public final class ByteReader implements Seq.Proxy, Reader {
	static { Core.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	ByteReader(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public ByteReader() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public final native Reader getReader();
	public final native void setReader(Reader v);
	
	public native long read(byte[] p0) throws Exception;
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof ByteReader)) {
		    return false;
		}
		ByteReader that = (ByteReader)o;
		Reader thisReader = getReader();
		Reader thatReader = that.getReader();
		if (thisReader == null) {
			if (thatReader != null) {
			    return false;
			}
		} else if (!thisReader.equals(thatReader)) {
		    return false;
		}
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getReader()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("ByteReader").append("{");
		b.append("Reader:").append(getReader()).append(",");
		return b.append("}").toString();
	}
}

