// Code generated by gobind. DO NOT EDIT.

// Java class go.kipfs.core.Closer is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=go.kipfs kipfs/core
//go:build  linux || windows 
//+build linux, windows 
package go.kipfs.core;

import go.Seq;

public interface Closer {
	public void close() throws Exception;
	
}

