// Code generated by gobind. DO NOT EDIT.

// Java class go.kipfs.core.Shell is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=go.kipfs kipfs/core
//go:build  linux || windows 
//+build linux, windows 
package go.kipfs.core;

import go.Seq;

public final class Shell implements Seq.Proxy {
	static { Core.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	public Shell(String url) {
		this.refnum = __NewShell(url);
		Seq.trackGoRef(refnum, this);
	}
	
	private static native int __NewShell(String url);
	
	Shell(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public native String dagPut(String data);
	public native RequestBuilder newRequest(String command);
	public native void test();
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof Shell)) {
		    return false;
		}
		Shell that = (Shell)o;
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("Shell").append("{");
		return b.append("}").toString();
	}
}

