FROM debian
RUN apt-get update && apt-get install -y \
    build-essential \
    default-jdk-headless \
   git \
    libssl-dev \
    nano \
    pkg-config \
    unzip \
    wget
#COPY root /

#RUN /setup.sh

#ENTRYPOINT /setup.sh


