// Code generated by gobind. DO NOT EDIT.

// Java class go.kipfs.files.DirIterator is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=go.kipfs github.com/ipfs/go-ipfs-files
//go:build  linux || windows 
//+build linux, windows 
package go.kipfs.files;

import go.Seq;

/**
 * DirIterator is a iterator over directory entries.
See Directory.Entries for more
 */
public interface DirIterator extends DirEntry {
	/**
	 * Err may return an error after previous call to Next() returned `false`.
	If previous call to Next() returned `true`, Err() is guaranteed to
	return nil
	 */
	public void err() throws Exception;
	public String name();
	/**
	 * Next advances iterator to the next file.
	 */
	public boolean next();
	public Node node();
	
}

