// Code generated by gobind. DO NOT EDIT.

// Java class go.kipfs.files.FileInfo is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=go.kipfs github.com/ipfs/go-ipfs-files
//go:build  linux || windows 
//+build linux, windows 
package go.kipfs.files;

import go.Seq;

/**
 * FileInfo exposes information on files in local filesystem
 */
public interface FileInfo extends Node {
	/**
	 * AbsPath returns full real file path.
	 */
	public String absPath();
	public void close() throws Exception;
	public long size() throws Exception;
	// skipped method FileInfo.Stat with unsupported parameter or return types
	
	
}

