// Code generated by gobind. DO NOT EDIT.

// Java class go.kipfs.files.Node is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=go.kipfs github.com/ipfs/go-ipfs-files
//go:build  linux || windows 
//+build linux, windows 
package go.kipfs.files;

import go.Seq;

/**
 * Node is a common interface for files, directories and other special files
 */
public interface Node {
	public void close() throws Exception;
	/**
	 * Size returns size of this file (if this file is a directory, total size of
	all files stored in the tree should be returned). Some implementations may
	choose not to implement this
	 */
	public long size() throws Exception;
	
}

