// Code generated by gobind. DO NOT EDIT.

// Java class go.kipfs.pubsub.Pubsub is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=go.kipfs kipfs/pubsub
//go:build  linux || windows 
//+build linux, windows 
package go.kipfs.pubsub;

import go.Seq;

public abstract class Pubsub {
	static {
		Seq.touch(); // for loading the native library
		go.kipfs.core.Core.touch();
		_init();
	}
	
	private Pubsub() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	private static final class proxySubscriptionListener implements Seq.Proxy, SubscriptionListener {
		private final int refnum;
		
		@Override public final int incRefnum() {
		      Seq.incGoRef(refnum, this);
		      return refnum;
		}
		
		proxySubscriptionListener(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
		
		public native void onMessage(String s);
	}
	
	
	public static native void subscribe(go.kipfs.core.Shell shell, String topic, SubscriptionListener listener);
}
