// Code generated by gobind. DO NOT EDIT.

// Java class go.kipfs.pubsub.PubSub is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=go.kipfs kipfs/pubsub
//go:build  linux || windows 
//+build linux, windows 
package go.kipfs.pubsub;

import go.Seq;

public final class PubSub implements Seq.Proxy {
	static { Pubsub.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	PubSub(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public PubSub() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public native Subscription newSubscription(go.kipfs.core.Shell shell, String topic, SubscriptionListener listener);
	public native void test();
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof PubSub)) {
		    return false;
		}
		PubSub that = (PubSub)o;
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("PubSub").append("{");
		return b.append("}").toString();
	}
}

