// Code generated by gobind. DO NOT EDIT.

// Java class go.kipfs.pubsub.SubscriptionListener is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=go.kipfs kipfs/pubsub
//go:build  linux || windows 
//+build linux, windows 
package go.kipfs.pubsub;

import go.Seq;

public interface SubscriptionListener {
	public void onMessage(String s);
	
}

