// Code generated by gobind. DO NOT EDIT.

// Java class kipfs.cids.Cids is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=kipfs kipfs/cids
package kipfs.cids;

import go.Seq;

public abstract class Cids {
	static {
		Seq.touch(); // for loading the native library
		System.out.println("Java: calling _init()");_init();System.out.println("Java: _init() done.");
	}
	
	private Cids() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	
	
	public static native String dagCid(String data);
	public static native String dagCidBytes(byte[] data, String format);
	public static native byte[] jsonToCbor(String json);
}
