// Code generated by gobind. DO NOT EDIT.

// Java class go.error is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=go.kipfs 
//go:build  linux || windows 
//+build linux, windows 
package go;

import go.Seq;

public interface error {
	public String error();
	
}

